// Copyright 2013 Weidong Liang. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package kmean

// Function SkClusterQuality evaluates the quality of the clusters generated by skmean algorithm.
func SkClusterQuality(clusters []Cluster) float64 {
	q := float64(0)
	for _, c := range clusters {
		for _, m := range c.Members {
			q += c.Centroid.CosineSim(m)
		}
	}
	return q
}

func NumberOfEmptyClusters(clusters []Cluster) int {
	n := 0
	for _, c := range clusters {
		if len(c.Members) == 0 {
			n++
		}
	}
	return n
}
